
logging:
  level:
    root: info
    com.fenyun.ws.manager.mapper: trace

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

shiro-redis:
  cluster:
    timeout: 10000
    host: localhost:6379
    name: user

